### ISSUE TITLE
Error message "error:0308010C:digital envelope routines::unsupported"

### ISSUE THREAD

**Issue by MrZaurik** [archcraft-os/documentation#25]
When the yarn server starts on the local machine, usually takes this error. Don't worry. I've have two solutions.
Downgrade nodejs or run: `export NODE_OPTIONS=--openssl-legacy-provider` on Unix Systems before run the server.

(In powershell: `$env:NODE_OPTIONS = "--openssl-legacy-provider"`)

![image](https://github.com/archcraft-os/documentation/assets/139176477/176c973f-c7b1-4656-aef3-ae9ec0ea356e)

**Comment by Z3r0Tw0-ZT** [comment]
Using this command can solve the issue
`npx yarn-audit-fix`

**Comment by adi1090x** [comment]
solved? 
Re-open if needed.
