### ISSUE TITLE
Hyprland Installation not work

### ISSUE THREAD

**Issue by kinjar1988** [archcraft-os/documentation#29]
Hello Archcraft os (Aditya)

As per your wiki guide To install hyprland, just run sudo pacman -Syyu archcraft-hyprland but when I run this command nothing happened. 

I am installing on Archcraft os with openbox.

Any other solution to install hyprland.

**Comment by adi1090x** [comment]
See [this](https://wiki.archcraft.io/docs/wayland-compositors/hyprland#installation)
